export const UPDATE_EVENTS = "UPDATE_EVENTS";
export const ADD_EVENTS = "ADD_EVENTS";

export const SET_GENRES = "SET_GENRES";
export const SET_SELECTED_GENRE = "SET_SELECTED_GENRE";

export const SET_SELECTED_DROPDOWN_ITEM_ID = "SET_SELECTED_DROPDOWN_ITEM_ID";